[package]
name = "aoc_2025"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
itertools = "0.14.0"
rustc-hash = "2.1.1"
regex = "1.12.2"
